### ISSUE TITLE
gt files

### ISSUE THREAD

**Issue by manyids2** [vbalnt/UBC-Phototour-Patches-Torch#1]
Dear vbalnt,
I downloaded the dataset 'notredame' from _http://phototour.cs.washington.edu/patches/default.htm_. However, it is missing the m50_100000_100000_0.txt and the m50_500000_500000_0.txt files. Where could I get them from? 
[context - I am using it to try the pnnet eval code, but it needs dataset.gt100k which is not created if the files are missing]

**Comment by vbalnt** [comment]
Hi, good catch I have given the wrong link for Brown's dataset, they seem to have two versions out

This is the correct link with the new files that also contain the gt files

http://www.cs.ubc.ca/~mbrown/patchdata/patchdata.html

I will also update the readme. 

Thanks

**Comment by manyids2** [comment]
Dear vbalnt,

Thank you so much for the quick response! And congratulations on the work, even the code is so awesomely readable :)
