### ISSUE TITLE
Can not download the converted dataset of .t7 format from provided link

### ISSUE THREAD

**Issue by fybaft2012** [vbalnt/UBC-Phototour-Patches-Torch#2]
Hi V. Balntas, I face the problem when I tried to download your converted dataset from the following links:
"wget http://www.iis.ee.ic.ac.uk/~vb2415/notredame-t7.tar.gz
wget http://www.iis.ee.ic.ac.uk/~vb2415/liberty-t7.tar.gz
wget http://www.iis.ee.ic.ac.uk/~vb2415/yosemite-t7.tar.gz"
 So can you help me how can I get them ? And my E-mail is fangyang968@gmail.com. 
Thank you very much!

**Comment by vbalnt** [comment]
Hi, the links were still pointing to the old website. I updated the links with the new adresses and now it should work. 

new site is ~vbalnt instead of ~vb2415, and the new links are now correct in the readme file of the repo. 

Thanks
Vassilis

**Comment by fybaft2012** [comment]
Ok, now it works. Thank you very much for your help!
