### ISSUE TITLE
Download dataset link not working

### ISSUE THREAD

**Issue by ste93ste** [vbalnt/UBC-Phototour-Patches-Torch#3]
The command

wget http://www.iis.ee.ic.ac.uk/~vbalnt/notredame-t7.tar.gz
wget http://www.iis.ee.ic.ac.uk/~vbalnt/liberty-t7.tar.gz
wget http://www.iis.ee.ic.ac.uk/~vbalnt/yosemite-t7.tar.gz

seems not work anymore.

**Comment by vbalnt** [comment]
Hi @ste93ste 

thanks for letting me know, some servers on Imperial College have issues, please try the new links below 

```
wget http://icvl.ee.ic.ac.uk/vbalnt/notredame-t7.tar.gz
wget http://icvl.ee.ic.ac.uk/vbalnt/liberty-t7.tar.gz
wget http://icvl.ee.ic.ac.uk/vbalnt/yosemite-t7.tar.gz
```

I have updated the readme with the new links. 

Thanks
